- name: Find CentOS repo files
  find:
    paths: /etc/yum.repos.d/
    patterns: 'CentOS-*'
  register: centos_repo_files

- name: Comment out mirrorlist
  replace:
    path: "{{ item.path }}"
    regexp: '^(mirrorlist.*)'
    replace: '#\1'
  loop: "{{ centos_repo_files.files }}"
  when: centos_repo_files.matched > 0

- name: Update baseurl
  replace:
    path: "{{ item.path }}"
    regexp: '^#baseurl=http://mirror.centos.org(.*)'
    replace: 'baseurl=http://vault.centos.org\1'
  loop: "{{ centos_repo_files.files }}"
  when: centos_repo_files.matched > 0